services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: aws-1-ap-south-1.pooler.supabase.com
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres.moybhtvaopxtydbnshhq
      - key: DB_POSTGRESDB_PASSWORD
        sync: false   # 👈 add manually in Render Dashboard
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"
 
