services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: aws-1-ap-south-1.pooler.supabase.com
      - key: DB_POSTGRESDB_PORT
        value: "5432"
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres.moybhtvaopxtydbnshhq
      - key: DB_POSTGRESDB_PASSWORD
        sync: false   # 👈 add manually in Render Dashboard
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"
 # EMAIL CONFIGURATION (SMTP)
      - key: N8N_EMAIL_MODE
        value: smtp
      - key: N8N_SMTP_HOST
        value: "smtp.zoho.com" # e.g., smtp.sendgrid.net
      - key: N8N_SMTP_PORT
        value: "465" # e.g., "587" for TLS or "465" for SSL
      - key: N8N_SMTP_USER
        sync: false   # 👈 add manually in Render Dashboard
      - key: N8N_SMTP_PASS
        sync: false   # 👈 add manually in Render Dashboard
      - key: N8N_SMTP_SENDER
        value: "Support<support@pharmalite.in>"
      - key: N8N_SMTP_SSL
        value: "true" # "true" if using SSL, "false" otherwise
